# Generated by Django 3.0.6 on 2020-06-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=200)),
                ('trend', models.BooleanField(default=False)),
                ('keys', models.CharField(max_length=200)),
                ('down', models.CharField(max_length=200)),
            ],
        ),
    ]
